name: .NET Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build and Validate
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore src/OrderStatusResilience.Api

    - name: Build solution
      run: dotnet build src/OrderStatusResilience.Api --configuration Release --no-restore

    - name: Confirm success
      run: echo "Build completed successfully"
